rawfile <- file("household_power_consumption.txt", "r")
cat(grep("(^Date)|(^[1|2]/2/2007)",readLines(rawfile), value=TRUE), sep="\n", file="filtered.txt")
close(rawfile)
filtered_data<-read.csv2("filtered.txt")
datetime<-strptime(paste(filtered_data$Date,filtered_data$Time), format= "%d/%m/%Y %H:%M:%S")
energy1<-as.numeric(as.character(filtered_data$Sub_metering_1))
energy2<-as.numeric(as.character(filtered_data$Sub_metering_2))
energy3<-as.numeric(as.character(filtered_data$Sub_metering_3))
png("plot3.png")
plot(datetime,energy1,type="l",col="black",xlab="",ylab="Energy sub metering")
lines(datetime,energy2,type="l",col="red")
lines(datetime,energy3,type="l",col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty = c(1,1,1))
dev.off()
